[env:nodemcu-32s]
platform = espressif32@6.5.0 ; Fixed version for better stability with NAPT
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
board_build.f_cpu = 240000000L

build_flags =
    -D IP_NAPT=1
    -D LWIP_FEATURES=1
    -D LWIP_IPV4=1

; This ensures the compiler finds the lwip headers correctly
lib_ldf_mode = deep+
