[env:esp32]
platform = espressif32
board = nodemcu-32s
framework = espidf
monitor_speed = 115200

; Fix 7: 2 MB Flash-Größe explizit setzen
board_build.flash_size = 2MB
board_build.partitions = partitions_2mb.csv
board_upload.flash_size = 2MB
